{% set version = "17.0.1" %}
{% set major_ver = version.split(".")[0] %}

package:
  name: polly
  version: {{ version }}

source:
  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version.replace(".rc", "-rc") }}/llvm-project-{{ version.replace(".rc", "rc") }}.src.tar.xz
  sha256: b0e42aafc01ece2ca2b42e3526f54bebc4b1f1dc8de6e34f46a0446a13e882b9

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - llvmdev =={{ version }}
  run:
    - llvmdev =={{ version }}

test:
  commands:
    - test -f $PREFIX/include/polly/ScopInfo.h                       # [not win]
    - test -f $PREFIX/include/polly/isl/isl-noexceptions.h           # [not win]
    - test -f $PREFIX/lib/libPollyISL.a                              # [not win]
    - test -f $PREFIX/lib/libPolly.a                                 # [not win]
    - test -f $PREFIX/lib/LLVMPolly.so                               # [not win]

about:
  home: https://polly.llvm.org/
  dev_url: https://github.com/llvm/llvm-project/polly
  license: Apache-2.0 WITH LLVM-exception
  license_file: polly/LICENSE.TXT
  license_family: Apache
  summary: Development headers and libraries for LLVM Polly

extra:
  recipe-maintainers:
    - lukastruemper
