{% set version = "17.0.3" %}
{% set major_ver = version.split(".")[0] %}

package:
  name: polly
  version: {{ version }}

source:
  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version.replace(".rc", "-rc") }}/llvm-project-{{ version.replace(".rc", "rc") }}.src.tar.xz
  sha256: be5a1e44d64f306bb44fce7d36e3b3993694e8e6122b2348608906283c176db8

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - llvmdev =={{ version }}
  run:
    - llvmdev =={{ version }}

test:
  commands:
    - test -f $PREFIX/include/polly/ScopInfo.h                       # [not win]
    - test -f $PREFIX/include/polly/isl/isl-noexceptions.h           # [not win]
    - test -f $PREFIX/lib/libPollyISL.a                              # [not win]
    - test -f $PREFIX/lib/libPolly.a                                 # [not win]
    - test -f $PREFIX/lib/LLVMPolly.so                               # [not win]

about:
  home: https://polly.llvm.org/
  dev_url: https://github.com/llvm/llvm-project/polly
  license: Apache-2.0 WITH LLVM-exception
  license_file: polly/LICENSE.TXT
  license_family: Apache
  summary: Development headers and libraries for LLVM Polly

extra:
  recipe-maintainers:
    - lukastruemper
